name: CIS Docker Audit

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          hostname
          whoami
          docker --version
          
      - name: Create .env
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env

      - name: Start Docker Lab
        run: |
          docker-compose up -d --build

      - name: Show containers
        run: docker ps

      - name: Run CIS audit
        run: |
          chmod +x audit/run_all.sh
          ./audit/run_all.sh
